### ISSUE TITLE
Linux 5 breaks USBGuard

### ISSUE THREAD

**Issue by ibahnasy** [USBGuard/usbguard#280] opened 2019-03-14 10:09 UTC
After upgrade to Linux 5 (Arch Linux), USBGuard is completely broken.

systemctl status usbguard
● usbguard.service - USBGuard daemon
   Loaded: loaded (/usr/lib/systemd/system/usbguard.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-03-14 12:12:27 EET; 3s ago
     Docs: man:usbguard-daemon(8)
  Process: 2887 ExecStart=/usr/bin/usbguard-daemon -f -s -c /etc/usbguard/usbguard-daemon.conf (code=exited, status=0/SUCCESS)
 Main PID: 2889 (usbguard-daemon)
    Tasks: 3 (limit: 4915)
   Memory: 4.0M
   CGroup: /system.slice/usbguard.service
           └─2889 /usr/bin/usbguard-daemon -f -s -c /etc/usbguard/usbguard-daemon.conf

Mar 14 12:12:27 myarch usbguard-daemon[2889]: Ignoring unknown UEvent action: sysfs_devpath=/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.1 a>
Mar 14 12:12:27 myarch usbguard-daemon[2889]: Ignoring unknown UEvent action: sysfs_devpath=/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0 a>
Mar 14 12:12:27 myarch usbguard-daemon[2889]: uid=0 pid=2887 device.rule='allow id 0bda:0129 serial "20100201396000000" name "USB2.0-CRW" hash >
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: Cannot resolve realpath for /sys/bus/usb/devices/../../../devices/pci0000:00/0000:00:14.0/usb1/1->
Mar 14 12:12:29 myarch usbguard-daemon[2889]: device enumeration exception: /sys/bus/usb/devices/1-8:1.0: SysFSDevice: uevent: No such file or >

**Comment by dkopecek** [comment] 2019-04-01 11:49
Hi, I couldn't reproduce the issue you are seeing on my system with 5.0.3 kernel. However, there's a similar report here: https://github.com/USBGuard/usbguard/issues/279, so I'll close this as a duplicate.

**Closed by dkopecek** 2019-04-01 11:49 UTC
Labels: C:libusbguard, C:usbguard-daemon, priority:high, resolution:duplicate
