### ISSUE TITLE
bring up on android

### ISSUE THREAD

**Issue by carl1314** [USBGuard/usbguard#414] opened 2020-09-08 05:51 UTC
Hi,
I want to know whether usbguard can bring up to android (android 8.1 for example),do u already have a try ?

**Comment by carl1314** [comment] 2020-09-08 05:56
I currently urgently need to implement the usb firewall function on android, so I plan to port usbguard to android.Could you kindly give some guide or suggestion?

**Comment by hartwork** [comment] 2022-02-19 17:09
My vote for closing this as a duplicate of #415 (which does have replies)

**Closed** 2022-02-23 10:51 UTC
